### ISSUE TITLE
Tinfoil shop are down

### ISSUE THREAD

**Issue by carcaschoi** [carcaschoi/ShallowSea#22]
I will add them back if they are ready

**Comment by henrymonster2000** [comment]
Thought I broke it when it stopped working yesterday. Hope this gets fixed soon.

**Comment by henrymonster2000** [comment]
> I will add them back if they are ready

Thought I broke it when it stopped working yesterday. Hope this gets fixed soon.

**Comment by carcaschoi** [comment]
> Thought I broke it when it stopped working yesterday. Hope this gets fixed soon.

Some of the link fix, update the aio package

**Comment by carcaschoi** [comment]
Fixed

**Comment by henrymonster2000** [comment]
> Fixed

What's fixed? Confused. 

I just tried Tinfoil and I still can't download from the shops (i.e. pengu, quota, etc.).

**Comment by carcaschoi** [comment]
> > Fixed
> 
> What's fixed? Confused.
> 
> I just tried Tinfoil and I still can't download from the shops (i.e. pengu, quota, etc.).

Update ShallowSea v2.0.1

**Comment by henrymonster2000** [comment]
> > > Fixed
> > 
> > 
> > What's fixed? Confused.
> > I just tried Tinfoil and I still can't download from the shops (i.e. pengu, quota, etc.).
> 
> Update ShallowSea v2.0.1

Brilliant. Thank you! Pengu is still not up yet but Quotashop's new address is working.
